-- MySQL Script generated by MySQL Workbench
-- Thu Jun 18 08:35:36 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vladyslavshusharin
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vladyslavshusharin
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vladyslavshusharin` DEFAULT CHARACTER SET utf8 ;
USE `vladyslavshusharin` ;

-- -----------------------------------------------------
-- Table `vladyslavshusharin`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vladyslavshusharin`.`Users` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Password` VARCHAR(300) NOT NULL,
  `Nickname` VARCHAR(45) NOT NULL,
  `Created` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Profile_Pic` VARCHAR(200) DEFAULT 'Profile_Pictures/default.jpg',
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vladyslavshusharin`.`Friends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vladyslavshusharin`.`Friends` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Status` ENUM('pending', 'accepted', 'blocked') NOT NULL,
  `Created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `User_ID` INT NOT NULL,
  `Friend_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_Friends_Users_idx` (`User_ID` ASC) VISIBLE,
  INDEX `fk_Friends_Users1_idx` (`Friend_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Friends_Users`
    FOREIGN KEY (`User_ID`)
    REFERENCES `vladyslavshusharin`.`Users` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Friends_Users1`
    FOREIGN KEY (`Friend_ID`)
    REFERENCES `vladyslavshusharin`.`Users` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vladyslavshusharin`.`Conversations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vladyslavshusharin`.`Conversations` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vladyslavshusharin`.`Conversation_participants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vladyslavshusharin`.`Conversation_participants` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `User_ID` INT NOT NULL,
  `Conversation_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_Conversation_participants_Users1_idx` (`User_ID` ASC) VISIBLE,
  INDEX `fk_Conversation_participants_Conversations1_idx` (`Conversation_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Conversation_participants_Users1`
    FOREIGN KEY (`User_ID`)
    REFERENCES `vladyslavshusharin`.`Users` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Conversation_participants_Conversations1`
    FOREIGN KEY (`Conversation_ID`)
    REFERENCES `vladyslavshusharin`.`Conversations` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vladyslavshusharin`.`Messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vladyslavshusharin`.`Messages` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Conversation_ID` INT NOT NULL,
  `Sender_ID` INT NOT NULL,
  `Message_content` VARCHAR(1000) NOT NULL,
  `Sent_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_Messages_Conversations1_idx` (`Conversation_ID` ASC) VISIBLE,
  INDEX `fk_Messages_Users1_idx` (`Sender_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Messages_Conversations1`
    FOREIGN KEY (`Conversation_ID`)
    REFERENCES `vladyslavshusharin`.`Conversations` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Messages_Users1`
    FOREIGN KEY (`Sender_ID`)
    REFERENCES `vladyslavshusharin`.`Users` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
